### ISSUE TITLE
azure/cli@v1 not working with azure/login@v1 on self-hosted runner

### ISSUE THREAD

**Issue by DeluxeOwl** [Azure/cli#71] opened 2022-01-28 09:01 UTC
Hi,

I'm running self hosted runners on k8s using https://github.com/actions-runner-controller/actions-runner-controller, which doesn't have `az cli` installed by default.  

So in my workflow, I'm installing it using `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` as per MS's documentation and signing in using `azure/login@v1` and a service account which works fine, but when I'm running `azure/cli@v1` right after, it gives the following errors:  

```sh
ERROR: Please run 'az login' to setup account.
Error: Error: az cli script failed.
```
![image](https://user-images.githubusercontent.com/54327698/151517578-c5025a12-afe4-4c01-89fc-9048ba116ee9.png)

here is how the github job looks:  
```yaml
  preview:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install az cli
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: azurecloud

      - uses: azure/cli@v1
        name: Run what-if
        with:
          inlineScript: |
            az deployment sub what-if --location ${{ env.RESOURCEGROUP_LOCATION }} \
              --template-file deploy/main.bicep
```

Any idea how to fix this?

**Comment by t-dedah** [comment] 2022-01-31 08:07
Hi @DeluxeOwl, this generally means that .azure folder is missing in the docker. Is it possible for your to confirm content of the agent using `ls` before `azure/cli` action and again inside the action? We want to confirm whether `.azure` folder is being created and copied correctly.

**Comment by DeluxeOwl** [comment] 2022-01-31 08:46
I've removed the deployment part and only did `ls -la`  
```yaml
  preview:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install az cli
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: azurecloud

      - run: ls -la ~ && ls -la ~/.azure/

      - uses: azure/cli@v1
        name: Run what-if
        with:
          inlineScript: |
            ls -la ~ && ls -la ~/.azure/
```
![image](https://user-images.githubusercontent.com/54327698/151763294-11aba15e-4a3c-4f81-903f-d483b817a012.png)  

It seems like the `.azure` directory is copied but is empty.

**Comment by damian-archlet** [comment] 2022-10-26 13:11
Have the exact same issue. My workaround was to just use the `azure/login@v1` action to login and then a `bash` step to run the rest of my pipeline. 
Would be nice to have it working though.

**Comment by hansmbakker** [comment] 2022-12-07 13:53
We have this issue, too. Workaround is to install az cli in the runner image or in the runner at runtime.

**Comment by MoChilia** [comment] 2023-04-21 06:34
Hi @DeluxeOwl, @damian-archlet, @hansmbakker! Please let us know if you are still facing the issue. I cannot reproduce the error, since azure/cli@v1 works well with azure/login@v1 on my self-hosted runner.

**Comment by DeluxeOwl** [comment] 2023-04-21 10:47
It's been one year and a few months since I opened this issue. I already switched jobs since then.

**Comment by MoChilia** [comment] 2023-04-23 01:25
Ok, thanks for your feedback. Closing this issue for now. If there is any further question, please reopen it.

**Closed by MoChilia** 2023-04-23 01:25 UTC
Labels: question
