### ISSUE TITLE
Error: Error: docker: invalid reference format.

### ISSUE THREAD

**Issue by Norrch2** [Azure/cli#74] opened 2022-03-21 18:44 UTC
Hello,

I am attempting to use Azure CLI to upload to a blob storage. I have followed the documentation and am receiving the error message displayed in the title of this bug request. "Error: Error: docker: invalid reference format."

Here is the github action yaml that I am using. 

```yml
- name: Upload To Blob Storage
   uses: azure/CLI@v1
   with:
     azcliversion: 2.34.1
     inlineScript: |
       az storage blob upload-batch -d $web -s ./dist/portal --account-name documentuploadstaticsite --overwrite
```

I have attempted several things to try to resolve this.

1. I have verified the source directory has files in it.
2. I have tested the az cli command locally and verified it works properly with no exceptions.
3. I have tested using different versions of Azure CLI.

I am all out of options, and any assistance would be greatly appreciated. 

Thank you.

**Comment by t-dedah** [comment] 2022-03-28 16:34
Hi @Norrch2 This looks like a docker issue. I suspect the issue is due to `$web`, can you try these steps:-

1. replace `$web` with random hardcoded value. If this works then we will be sure that the issue is due to `$web`.
2. Then try `${web}` or `$(web)`

**Comment by Norrch2** [comment] 2022-03-28 20:10
Hello @t-dedah 

I have tried changing it to a hard coded value and the problem still persists. I have included two screenshots, 1 being the error and the second being the change I made to the yaml. 

![image](https://user-images.githubusercontent.com/16027559/160478698-626cedc0-4f43-488c-9df3-ad1e81935e66.png)
![image](https://user-images.githubusercontent.com/16027559/160478816-c973f8ac-f876-42fc-8ebf-68a555983af6.png)

**Comment by Norrch2** [comment] 2022-03-28 20:10
I have tried using different action versions and cli versions.

**Comment by Norrch2** [comment] 2022-03-29 16:31
is there a way I can run the docker command line on my local machine to be able to troubleshoot that way? I am not certain as to what the CLI command that is being provided by docker is to test.

**Comment by t-dedah** [comment] 2022-03-30 09:11
Hi @Norrch2 I tried to reproduce the error but failed to do in the call cases. I used `runs-on: ubuntu-latest`.
Can you please share your `runs-on` field? If its `ubuntu-latest` too then can you please help me reproducing this error? 

I tried this and got an error related to `--acount-name` not being a valid parameter but not the docker error.
```yaml
- name: Upload To Blob Storage
   uses: azure/CLI@v1
   with:
     azcliversion: 2.34.1
     inlineScript: |
       az storage blob upload-batch -d $web -s ./dist/portal --acount-name documentuploadstaticsite --overwrite
```

**Comment by Norrch2** [comment] 2022-03-30 10:41
Hi @t-dedah 

Please try the following: copied and pasted. (account was misspelled) 

```
  runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Web

- name: Upload To Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.34.1
        inlineScript: |
          az storage blob upload-batch --account-name documentuploadstaticsite -d '$web' -s ./dist/portal
```

**Comment by Norrch2** [comment] 2022-04-04 20:15
Hello. May I have an update on this?

**Comment by t-dedah** [comment] 2022-04-08 10:45
Hi @Norrch2, I tried multiple combinations and still not able to reproduce the issue.

I tried this and it worked perfectly fine.

```
- name: Upload To Blob Storage
  uses: azure/CLI@v1
  with:
    azcliversion: 2.34.1
    inlineScript: |
      az storage blob upload-batch --account-key ${{ secrets.ACCOUNT_KEY }} --account-name deepakstorage -d test -s ./src
```

**Comment by Norrch2** [comment] 2022-04-11 03:24
Is there a way to see the docker command that is executed so perhaps I can execute it locally and get an error I can work with?

**Comment by Norrch2** [comment] 2022-04-11 03:51
Okay so it looks like the problem was due to environment variables on the Environment scope instead of the job scope.

The following environment variables were defined and the action didn't like them:

AZURE_FUNCTIONAPP_NAME: randomappname
      AZURE_FUNCTIONAPP_PACKAGE_PATH: randomappname\published
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.randomappname_FFFF }}
      CONFIGURATION: Release
      DOTNET_CORE_VERSION: 6.0.x
      WORKING_DIRECTORY: randomappname

**Comment by t-dedah** [comment] 2022-04-13 05:39
@Norrch2 Thank you for the info. As the issue is resolved now, I am closing the issue. Feel free to reopen if you face any more issues.

**Closed by t-dedah** 2022-04-13 05:39 UTC
Labels: waiting-for-customer
