### ISSUE TITLE
az cli script failed in github action.

### ISSUE THREAD

**Issue by pawan885** [Azure/cli#121] opened 2023-11-02 14:02 UTC
[logs_1247.zip](https://github.com/Azure/cli/files/13239677/logs_1247.zip)
attaching log here to investigate

**Comment by MoChilia** [comment] 2023-11-08 02:26
Hi @pawan885, 
I've reviewed your attachments. The error occurs when you check if the secret `yy` already exists in:
``` secretExists=$(az keyvault secret show --vault-name "$AZURE_KEYVAULT_NAME" --name "$secret" 2>/dev/null) ```
You've redirected the error message to `/dev/null`, making it impossible to see what the error is. Please remove `2>/dev/null` and include the error message of `az keyvault secret show`.

**Comment by MoChilia** [comment] 2023-12-14 05:21
I will close this issue since it doesn't seem to be caused by GitHub action. If you encounter any other question, please feel free to reopen it and attach the error message.

**Closed by MoChilia** 2023-12-14 05:21 UTC
Labels: question
